#!/bin/bash
# Getting
export CHATID="1830342336"
export KEY="6320035110:AAE6otySdlNHPhKom2PNtp8yZn8X8rZS7LE"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
VALIDITY () {
    today=`date -d "0 days" +"%Y-%m-%d"`
    Exp1=$(curl https://raw.githubusercontent.com/Jegkolonline/izinn/main/ip | grep $MYIP | awk '{print $4}')
    if [[ $today < $Exp1 ]]; then
    echo -e "\e[32mYOUR SCRIPT ACTIVE..\e[0m"
    else
echo -e "${Lyellow}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${Lred}                PERMISSION DENIED ! ${NC}"
echo -e "${Lyellow}     Your VPS ${NC}( ${green}$MYIP${NC} ) ${Lyellow}Has been Banned "
echo -e "         Buy access permissions for scripts "
echo -e "                 Contact Admin :"
echo -e "             ${green}Telegram t.me/Jengkol_Online "
echo -e "             WhatsApp wa.me/6282372139631"
echo -e "${Lyellow}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    exit 0
fi
}
IZIN=$(curl https://raw.githubusercontent.com/Jengkolonline/izinn/main/ip | awk '{print $5}' | grep $MYIP)
if [ $MYIP = $IZIN ]; then
echo -e "\e[32mPermission Accepted...\e[0m" >/dev/null 2>&1
VALIDITY
else
echo -e "\e[31mPermission Denied!\e[0m";
echo -e "\e[31mPlease buy script first\e[0m"
exit 0
fi
echo -e "\e[32mloading...\e[0m"
clear
RDP="https://raw.githubusercontent.com/Jengkolonline/XRAY/main/"
WEBU="http://files.webuzo.com/install.sh"
VESTA="http://vestacp.com/pub/vst-install.sh"
UI="(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v1.6.1"
PT="(curl -s https://pterodactyl-installer.se)"
CB="https://cyberpanel.net/install.sh"
UPDATE="https://raw.githubusercontent.com/Jengkolonline/XRAY/main/"
BOT="https://raw.githubusercontent.com/Jengkolonline/XRAY/main/"
UDPCORE="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
NTN="https://raw.githubusercontent.com/Jengkolonline/nonton/main/nf.sh"
clear
echo -e " \033[31m##########\033[33m##########\033[32m##########\033[34m##########\033[35m##########\033[36m##########\e[0m"
echo -e " \033[31m╭══════════════════════════════════════════════════════════╮\e[0m"
echo -e " \033[34m│$NC\033[33m                   MENU Install Panel                     $NC\033[34m│\e[0m"
echo -e " \033[33m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e " \033[32m╭══════════════════════════════════════════════════════════╮\e[0m"
echo -e " \033[35m│$NC [01]${NC} \033[0;36m Installer DNS Global Netflix, YouTube dll${NC}"
echo -e " \033[35m│$NC [02]${NC} \033[0;36m Installer RDP${NC}"
echo -e " \033[35m│$NC [03]${NC} \033[0;36m Installer WEBUZO${NC}"
echo -e " \033[35m│$NC [04]${NC} \033[0;36m Installer VESTA${NC}"
echo -e " \033[35m│$NC [05]${NC} \033[0;36m Installer UI B.Inggris${NC}"
echo -e " \033[35m│$NC [06]${NC} \033[0;36m Installer PTERODACTYL${NC}"
echo -e " \033[35m│$NC [07]${NC} \033[0;36m Installer CYBERPANEL${NC}"
echo -e " \033[35m│$NC [08]${NC} \033[0;36m Installer WEBMIN${NC}"
echo -e " \033[36m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e " \033[31m##########\033[33m##########\033[32m##########\033[34m##########\033[35m##########\033[36m##########\e[0m"
echo -e ""
read -p " Select From Options [ 1 - 5 ] : " menu
case $menu in
1) clear ; wget ${NTN} && chmod +x nf.sh && ./nf.sh ; exit ;;
2) clear ; wget ${RDP}/foldder/ins-rdp.sh && chmod +x ins-rdp.sh && ./ins-rdp.sh ; exit ;;
3) clear ; wget -N ${WEBU} && chmod 0755 install.sh && ./install.sh ; exit ;;
4) clear ; curl ${VESTA} | bash ; exit ;;
5) clear ; bash ${UI} ; exit ;;
6) clear ; bash ${PT} ; exit ;;
7) clear ; wget -O installer.sh ${CB} && chmod +x install.sh && ./install.sh ; exit ;;
8) clear ; webmin ; exit ;;
*) clear ; menu ; exit ;;
esac
