#!/bin/bash
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
# Getting

ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
PUB=$( cat /etc/slowdns/server.pub )
NS=`cat /etc/xray/dns`
clear
IP=$(curl -sS ipv4.icanhazip.com)
Login=Trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
hari="1"
Pass=1
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo ""
mkdir -p /etc/ssh

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${Login} " >>/etc/ssh/.ssh.db
echo ""

cat >/var/www/html/ssh-$Login.txt <<-END
====================
JengkolOnline Tunneling
====================
SSH OVPN Account    
====================
Username         : $Login
Password         : $Pass
IP               : $IP
Host             : $domain
Host Slowdns     : ${NS}
Pub Key          : ${PUB}
Location         : $CITY
Port OpenSSH     : 443, 80, 22
Port DNS         : 443, 53 ,22 
Port SSH UDP     : 1-65535
Port Dropbear    : 443, 109
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
SSH-NOSSL-WS     : 8880
Port SSL/TLS     : 442,443,444,777
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
OHP Dropbear     : 8585
OHP SSH          : 8686
OHP OpenVPN      : 8787
BadVPN UDP       : 7100, 7300, 7300
====================
Tinggal Copy Prot 80  : ${domain}:80@${Login}:${Pass}
Tinggal Copy Prot 443 : ${domain}:443@${Login}:${Pass}
====================
UDP Account : ${domain}:1-65535@${Login}:${Pass}
====================
Link Download OpenVpn
OpenVpn TCP     : https://${domain}:81/tcp.ovpn
OpenVpn UDP     : https://${domain}:81/udp.ovpn
OpenVpn SSL     : https://${domain}:81/ssl.ovpn
OpenVpn ws SSL  : https://${domain}:81/ws-ssl.ovpn
OpenVpn All Zip : https://${domain}:81/Geo-Project.zip
====================
Link Download OHP
OpenVPN OHP      : 8787 http://$MYIP:81/client-tcp-ohp1194.ovpn
====================
Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]
====================
Berakhir Pada    : 60 Menit
====================
END

clear
echo -e ""
echo -e "\033[1;93m====================\033[0m"
echo -e "  Trial SSH & OpenVPN"
echo -e "\033[1;93m====================\033[0m"
echo -e "Username         : $Login"
echo -e "Password         : $Pass"
echo -e "IP               : $IP"
echo -e "Host             : $domain"
echo -e "Host Slowdns     : ${NS}"
echo -e "Pub Key          : ${PUB}"
echo -e "Location         : $CITY"
echo -e "Port OpenSSH     : 443, 80, 22"
echo -e "Port DNS         : 443, 53 ,22 "
echo -e "Port SSH UDP     : 1-65535"
echo -e "Port Dropbear    : 443, 109"
echo -e "Port SSH WS      : 80, 8080, 8081-9999"
echo -e "Port SSH SSL WS  : 443"
echo -e "SSH-NOSSL-WS     : 8880"
echo -e "Port SSL/TLS     : 442,443,444,777"
echo -e "Port OVPN WS SSL : 443"
echo -e "Port OVPN SSL    : 443"
echo -e "Port OVPN TCP    : 443, 1194"
echo -e "Port OVPN UDP    : 2200"
echo -e "OHP Dropbear     : 8585"
echo -e "OHP SSH          : 8686"
echo -e "OHP OpenVPN      : 8787"
echo -e "BadVPN UDP       : 7100, 7300, 7300"
echo -e "\033[1;93m====================\033[0m"
echo -e "Tinggal Copy Prot 80  : ${domain}:80@${Login}:${Pass}"
echo -e "Tinggal Copy Prot 443 : ${domain}:443@${Login}:${Pass}"
echo -e "\033[1;93m====================\033[0m"
echo -e " UDP Account : ${domain}:1-65535@${Login}:${Pass}"
echo -e "\033[1;93m====================\033[0m"
echo -e "Link Download OpenVpn"
echo -e "OpenVpn TCP     : https://${domain}:81/tcp.ovpn"
echo -e "OpenVpn UDP     : https://${domain}:81/udp.ovpn"
echo -e "OpenVpn SSL     : https://${domain}:81/ssl.ovpn"
echo -e "OpenVpn ws SSL  : https://${domain}:81/ws-ssl.ovpn"
echo -e "OpenVpn All Zip : https://${domain}:81/Geo-Project.zip"
echo -e "\033[1;93m====================\033[0m"
echo -e "Link Download OHP"
echo -e "OpenVPN OHP : 8787 http://$MYIP:81/client-tcp-ohp1194.ovpn"
echo -e "\033[1;93m====================\033[0m"
echo -e "Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "\033[1;93m====================\033[0m"
echo -e "Link Txt : https://${domain}:81/ssh-${Login}.txt"
echo -e "\033[1;93m====================\033[0m"
echo -e "Berakhir Pada  : 60 Menit"
echo -e "\033[1;93m====================\033[0m"
echo "killtrial ssh ${Login}" | at now +60 minutes &> /dev/null

fi
